pipeline {
    options{
        timeout(time: 30, unit: 'MINUTES')
    }
    agent{
        node{
            label 'master'
        }
    }
    environment{
        NAME=YPYP
    }
    stages{
        stage('stage 1'){
            steps{
                sh "SAAAAA"
            }
        }
        stage('stage 2'){
            steps{
                timeout(time: 60, unit: 'MINUTES') {
                input message: "Move to stage 3?"
            }
        }
        stage('stage 3'){
            steps{
                script {
                    openshift.withCluster() {
                        openshift.withProject() {
                                echo "stage 1: using project: ${openshift.project()} in cluster ${openshift.cluster()}"
                        }
                    }
                }
            }
        }
    }
}
